name: Bump versions

on: [workflow_dispatch]

jobs:
  bump-versions:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_CI_PASSWORD }}
      - id: bump-version
        name: Bump Version (Patch)
        run: |
          git config --global user.email "${{ secrets.GIT_CI_EMAIL }}"
          git config --global user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:${{secrets.GIT_CI_PASSWORD }}@github.com/${{ github.repository }}
          PACKAGE_VERSION=$(npm version patch -m "bump: update version to %s [skip ci]")
          echo "patch $GITHUB_REF_NAME bump version $PACKAGE_VERSION for $GITHUB_ACTOR $GITHUB_REF"
          echo >> RELEASE.md && echo "## version:$PACKAGE_VERSION issued date $(date)" >>RELEASE.md \ && echo >> RELEASE.md \
          && echo "link:(https://github.com/terra-rebirth/crypto-bot/releases/tag/$PACKAGE_VERSION)" >>RELEASE.md \
          && echo >> RELEASE.md
          git add .
          git commit -m 'skip ci'
          git push
          git pull --rebase origin main
          git push origin $PACKAGE_VERSION
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"
      - name: Trigger release workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: Release & Docker
          client-payload:
            '{"ref": "${{ steps.bump-version.outputs.PACKAGE_VERSION }}"}'


